spring.application.name=traceops-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/traceops
spring.datasource.username=traceops
spring.datasource.password=traceops

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
